spring.application.name=demo
spring.profiles.active=dev
server.port=0
logging.level.org.springframework=INFO
spring.datasource.url=jdbc:postgresql://localhost:5432/crach?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=az
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.cache=false
spring.main.allow-bean-definition-overriding=true
spring.jackson.serialization.indent-output=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.livereload.port=35729
spring.devtools.livereload.delay=1000
spring.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
spring.web.resources.cache.period=3600
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**
spring.web.resources.chain.cache=true
spring.web.resources.chain.compressed=true
spring.web.resources.chain.html-application-cache.enabled=true
spring.web.resources.chain.html-application-cache.paths=/**
spring.mail.host=smtp.example.com
spring.mail.port=587


